name: $(BuildDefinitionName)-$(Rev:rrr)

trigger: 
  branches:
    include:
      - main

pr: none

variables: 
  DSC_OUTPUT_FOLDER: ./Output
  DSC_DEFINITIONS_FOLDER: ./DSC

  kpmg_uk_ewt_prd_serviceConnection: 'sc-epac-dev'

pool:
  vmImage: 'windows-latest'

stages:
  - stage: build
    displayName: Build DSC packages
    jobs:
      - template: templates/job-build-DSC.yml
        parameters:
          serviceConnection: $(kpmg_uk_ewt_prd_serviceConnection)
  
  - stage: deploy
    displayName: Deploy DSC packages
    dependsOn:
      - build
    jobs:
      - deployment: deploy
        displayName: Deploy DSC packages
        environment: DSC
        variables:
          DSC_INPUT_FOLDER: "$(Pipeline.Workspace)"
          DSC_OUTPUT_FOLDER: "$(Pipeline.Workspace)/DSC"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - download: current
                  artifact: DSC
                - task: AzurePowerShell@5
                  name: deployStep
                  displayName: Deploy
                  inputs:
                    azureSubscription: $(kpmg_uk_ewt_prd_serviceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy-GuestConfiguration.ps1" 
                    ScriptArguments: 
                      -storageAccountName stmockpmgtfdev001
                      -storageContainerName guestconfig
                      -InformationAction Continue
